apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  labels:
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  # pod spec begins here
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: registry.digitalocean.com/flask-tutorial-registry/flask-tutorial:0.0.1 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
